import { CdfiEditFormData } from 'types';

export const cdfiEditDefaultValues: CdfiEditFormData = {
    name: '',
    address: '',
    address2: '',
    city: '',
    state: '',
    zip: '',
    country: '',
    areasServed: [],
    companyType: '',
    description: '',
    fax: '',
    phone: '',
    phoneExtension: '',
    ratedSince: '',
    website: '',
    fiscalYearEnd: '',
    otherLendingTypes: [],
    primaryLendingTypes: [],
    assetSize: '',
    ein: '',
    organizationType: '',
    taxType: '',
    targetBeneficiaries: [],
    tags: [],
    hideActivity: false,
    reportAllRows: false,
    active: false,
    rated: false,
    taxJurisdiction: '',
    shareFinancials: '',
    peerGroupAllowed: false,
    suppressReminders: false,
    mission: '',
    impactAreas: [],
    subImpactAreas: [],
    startRequestingYear: '',
    startRequestingQuarter: '',
    emailReminders: '',
};