export const notificationTypes = Object.freeze({
  METRIC_VALUE_CHANGED: 'METRIC_VALUE_CHANGED',
  METRIC_REPORT_REQUEST: 'METRIC_REPORT_REQUEST',
  METRIC_VALUE_RESPONSE: 'METRIC_VALUE_RESPONSE',
  METRIC_VALUE_CHANGE_REQUEST: 'METRIC_VALUE_CHANGE_REQUEST',
  METRIC_REPORT_RESPONSE: 'METRIC_REPORT_RESPONSE',
  METRIC_VALUE_REPORT_RECEIVED: 'METRIC_VALUE_REPORT_RECEIVED',
  PC_UNSUBSCRIBE: 'PC_UNSUBSCRIBE',
  FM_UNSUBSCRIBE: 'FM_UNSUBSCRIBE',
  DATA_ENTRY_REMINDER: 'DATA_ENTRY_REMINDER',
});
