import { UserRole } from 'types';
import { cdfiStore, subscriberStore } from '../../../../store';
import { ManagementMenuItem } from '../components/types';
import { DownloadTitles } from '../constants';
import { useAppConfig } from '../../../../useAppConfig';

const { viewModeConfig: cdfiConfig } = cdfiStore;
const { viewModeConfig: subscriberConfig } = subscriberStore;

export const adminCdfiSelectedItems = (
  isRated?: boolean,
  isSupplementalDataEnabled?: boolean,
): Record<UserRole, ManagementMenuItem[]> => {
  return {
    [UserRole.AERIS_ADMIN]: [
      {
        key: 'cdfiselector',
        title: 'CDFI SELECTOR',
        path: '/cdfiSelector',
        icon: 'filesearch',
      },
      {
        key: 'aerisexp',
        title: 'GLOBAL PEER GROUPS',
        path: '/aerisExplorer/global',
        icon: 'auditicon',
      },
      {
        key: 'managecdfi',
        title: 'MANAGE',
        path: '/',
        divider: true,
      },
      {
        key: 'manage',
        title: 'DASHBOARD',
        path: `/manage/cdfi/${cdfiConfig.cdfiId}`,
        icon: 'dashboardicon',
        disabled: false,
        children: [],
      },
      {
        key: 'manage',
        title: 'RATINGS',
        path: `/manage/cdfi/${cdfiConfig.cdfiId}/ratings`,
        icon: 'staricon',
        disabled: false,
        children: [],
      },
      {
        key: 'manage',
        title: 'SUBSCRIBERS',
        path: `/manage/cdfi/${cdfiConfig.cdfiId}/subscribers`,
        icon: 'filedoneicon',
        disabled: false,
        children: [],
      },
      {
        key: 'manage',
        title: 'FINANCIALS',
        path: `/manage/cdfi/${cdfiConfig.cdfiId}/financials`,
        icon: 'dollaricon',
        disabled: false,
        children: [],
      },
      ...(isSupplementalDataEnabled
        ? [
            {
              key: 'manage',
              title: 'SUPPLEMENTAL',
              path: `/manage/cdfi/${cdfiConfig.cdfiId}/supplemental`,
              icon: 'fundicon',
              disabled: false,
              children: [],
            },
          ]
        : []),
      {
        key: '',
        title: 'MANAGE CDFI',
        path: '/',
        divider: true,
      },
      {
        key: 'manage',
        title: 'ORGANIZATION DETAILS',
        path: `/manage/cdfi/${cdfiConfig.cdfiId}/org-details`,
        icon: 'idcardicon',
        disabled: false,
        children: [],
      },
      {
        key: 'contacts',
        title: 'CONTACTS',
        path: `/manage/cdfi/${cdfiConfig.cdfiId}/contacts`,
        icon: 'teamicon',
        disabled: false,
        children: [],
      },
      {
        key: 'manage',
        title: 'LIBRARY',
        path: `/manage/cdfi/${cdfiConfig.cdfiId}/library`,
        icon: 'readicon',
        disabled: false,
        children: [],
      },
      {
        key: 'metrics',
        title: 'METRICS',
        path: `/manage/cdfi/${cdfiConfig.cdfiId}/metrics`,
        icon: 'barcharticon',
        disabled: false,
        children: [],
      },
      {
        key: 'required-metrics',
        title: 'REQUIRED METRICS',
        path: `/manage/cdfi/${cdfiConfig.cdfiId}/required-metrics`,
        icon: 'requiredmetrics',
        disabled: false,
        children: [],
      },
      {
        key: 'periods',
        title: 'PERIODS',
        path: `/manage/cdfi/${cdfiConfig.cdfiId}/periods`,
        icon: 'periods',
        disabled: false,
        children: [],
      },
      {
        key: 'graphs',
        title: 'GRAPHS',
        path: `/manage/cdfi/${cdfiConfig.cdfiId}/graphs`,
        icon: 'piecharticon',
        disabled: false,
        children: [],
      },
      {
        key: 'manage',
        title: 'ANALYSTS',
        path: `/manage/cdfi/${cdfiConfig.cdfiId}/analysts`,
        icon: 'contacts',
        disabled: false,
        children: [],
      },
      {
        key: 'downloads',
        title: 'Downloads',
        path: '/',
        icon: 'downloadicon',
        disabled: false,
        children: [
          {
            key: 'factsheet',
            title: DownloadTitles.FACT_SHEET,
            path: '/',
            disabled: false,
            children: [],
          },
          {
            key: 'ratingcert',
            title: DownloadTitles.RATING_CERTIFICATE,
            path: '/',
            disabled: !isRated,
            children: [],
          },
          {
            key: 'aerislogos',
            title: 'Aeris-Rated Logos',
            path: `/manage/cdfi/${cdfiConfig.cdfiId}/ratings`,
            disabled: false,
            children: [],
          },
        ],
      },
      {
        key: 'aerisexplorer',
        title: 'CDFI EXPLORER',
        path: `/aerisexplorer/cdfi/${cdfiConfig.cdfiId}`,
        icon: 'auditicon',
        disabled: false,
        children: [],
      },
      {
        key: 'supporthistory',
        title: 'SUPPORT HISTORY',
        path: `/manage/cdfi/${cdfiConfig.cdfiId}/support-history`,
        icon: 'customerservice',
        disabled: false,
        children: [],
      },
    ],
    [UserRole.AERIS_STAFF]: [
      {
        key: 'cdfiselector',
        title: 'CDFI SELECTOR',
        path: '/cdfiSelector',
        icon: 'filesearch',
      },
      {
        key: 'aerisexp',
        title: 'GLOBAL PEER GROUPS',
        path: '/aerisExplorer/global',
        icon: 'auditicon',
      },
      {
        key: 'managecdfi',
        title: 'MANAGE',
        path: '/',
        divider: true,
      },
      {
        key: 'manage',
        title: 'DASHBOARD',
        path: `/manage/cdfi/${cdfiConfig.cdfiId}`,
        icon: 'dashboardicon',
        disabled: false,
        children: [],
      },
      {
        key: 'manage',
        title: 'RATINGS',
        path: `/manage/cdfi/${cdfiConfig.cdfiId}/ratings`,
        icon: 'staricon',
        disabled: false,
        children: [],
      },
      {
        key: 'manage',
        title: 'SUBSCRIBERS',
        path: `/manage/cdfi/${cdfiConfig.cdfiId}/subscribers`,
        icon: 'filedoneicon',
        disabled: false,
        children: [],
      },
      {
        key: 'manage',
        title: 'FINANCIALS',
        path: `/manage/cdfi/${cdfiConfig.cdfiId}/financials`,
        icon: 'dollaricon',
        disabled: false,
        children: [],
      },
      ...(isSupplementalDataEnabled
        ? [
          {
            key: 'manage',
            title: 'SUPPLEMENTAL',
            path: `/manage/cdfi/${cdfiConfig.cdfiId}/supplemental`,
            icon: 'fundicon',
            disabled: false,
            children: [],
          },
        ]
        : []),
      {
        key: '',
        title: 'MANAGE CDFI',
        path: '/',
        divider: true,
      },
      {
        key: 'manage',
        title: 'ORGANIZATION DETAILS',
        path: `/manage/cdfi/${cdfiConfig.cdfiId}/org-details`,
        icon: 'idcardicon',
        disabled: false,
        children: [],
      },
      {
        key: 'contacts',
        title: 'CONTACTS',
        path: `/manage/cdfi/${cdfiConfig.cdfiId}/contacts`,
        icon: 'teamicon',
        disabled: false,
        children: [],
      },
      {
        key: 'manage',
        title: 'LIBRARY',
        path: `/manage/cdfi/${cdfiConfig.cdfiId}/library`,
        icon: 'readicon',
        disabled: false,
        children: [],
      },
      {
        key: 'metrics',
        title: 'METRICS',
        path: `/manage/cdfi/${cdfiConfig.cdfiId}/metrics`,
        icon: 'barcharticon',
        disabled: false,
        children: [],
      },
      {
        key: 'required-metrics',
        title: 'REQUIRED METRICS',
        path: `/manage/cdfi/${cdfiConfig.cdfiId}/required-metrics`,
        icon: 'requiredmetrics',
        disabled: false,
        children: [],
      },
      {
        key: 'periods',
        title: 'PERIODS',
        path: `/manage/cdfi/${cdfiConfig.cdfiId}/periods`,
        icon: 'periods',
        disabled: false,
        children: [],
      },
      {
        key: 'graphs',
        title: 'GRAPHS',
        path: `/manage/cdfi/${cdfiConfig.cdfiId}/graphs`,
        icon: 'piecharticon',
        disabled: false,
        children: [],
      },
      {
        key: 'manage',
        title: 'ANALYSTS',
        path: `/manage/cdfi/${cdfiConfig.cdfiId}/analysts`,
        icon: 'contacts',
        disabled: false,
        children: [],
      },
      {
        key: 'downloads',
        title: 'Downloads',
        path: '/',
        icon: 'downloadicon',
        disabled: false,
        children: [
          {
            key: 'factsheet',
            title: DownloadTitles.FACT_SHEET,
            path: '/',
            disabled: false,
            children: [],
          },
          {
            key: 'ratingcert',
            title: DownloadTitles.RATING_CERTIFICATE,
            path: '/',
            disabled: !isRated,
            children: [],
          },
          {
            key: 'aerislogos',
            title: 'Aeris-Rated Logos',
            path: `/manage/cdfi/${cdfiConfig.cdfiId}/ratings`,
            disabled: false,
            children: [],
          },
        ],
      },
      {
        key: 'aerisexplorer',
        title: 'CDFI EXPLORER',
        path: `/aerisexplorer/cdfi/${cdfiConfig.cdfiId}`,
        icon: 'auditicon',
        disabled: false,
        children: [],
      },
      {
        key: 'supporthistory',
        title: 'SUPPORT HISTORY',
        path: `/manage/cdfi/${cdfiConfig.cdfiId}/support-history`,
        icon: 'customerservice',
        disabled: false,
        children: [],
      },
    ],
    [UserRole.CONTRACTOR]: [
      {
        key: 'cdfiselector',
        title: 'CDFI SELECTOR',
        path: '/cdfiSelector',
        icon: 'filesearch',
      },
      {
        key: 'managecdfi',
        title: 'MANAGE',
        path: '/',
        divider: true,
      },
      {
        key: 'manage',
        title: 'DASHBOARD',
        path: `/manage/cdfi/${cdfiConfig.cdfiId}`,
        icon: 'dashboardicon',
        disabled: false,
        children: [],
      },
      {
        key: 'manage',
        title: 'RATINGS',
        path: `/manage/cdfi/${cdfiConfig.cdfiId}/ratings`,
        icon: 'staricon',
        disabled: false,
        children: [],
      },
      {
        key: 'manage',
        title: 'SUBSCRIBERS',
        path: `/manage/cdfi/${cdfiConfig.cdfiId}/subscribers`,
        icon: 'filedoneicon',
        disabled: false,
        children: [],
      },
      {
        key: 'manage',
        title: 'FINANCIALS',
        path: `/manage/cdfi/${cdfiConfig.cdfiId}/financials`,
        icon: 'dollaricon',
        disabled: false,
        children: [],
      },
      {
        key: '',
        title: 'MANAGE CDFI',
        path: '/',
        divider: true,
      },
      {
        key: 'manage',
        title: 'ORGANIZATION DETAILS',
        path: `/manage/cdfi/${cdfiConfig.cdfiId}/org-details`,
        icon: 'idcardicon',
        disabled: false,
        children: [],
      },
      {
        key: 'contacts',
        title: 'CONTACTS',
        path: `/manage/cdfi/${cdfiConfig.cdfiId}/contacts`,
        icon: 'teamicon',
        disabled: false,
        children: [],
      },
      {
        key: 'manage',
        title: 'LIBRARY',
        path: `/manage/cdfi/${cdfiConfig.cdfiId}/library`,
        icon: 'readicon',
        disabled: false,
        children: [],
      },
      {
        key: 'metrics',
        title: 'METRICS',
        path: `/manage/cdfi/${cdfiConfig.cdfiId}/metrics`,
        icon: 'barcharticon',
        disabled: false,
        children: [],
      },
      {
        key: 'required-metrics',
        title: 'REQUIRED METRICS',
        path: `/manage/cdfi/${cdfiConfig.cdfiId}/required-metrics`,
        icon: 'requiredmetrics',
        disabled: false,
        children: [],
      },
      {
        key: 'periods',
        title: 'PERIODS',
        path: `/manage/cdfi/${cdfiConfig.cdfiId}/periods`,
        icon: 'periods',
        disabled: false,
        children: [],
      },
      {
        key: 'graphs',
        title: 'GRAPHS',
        path: `/manage/cdfi/${cdfiConfig.cdfiId}/graphs`,
        icon: 'piecharticon',
        disabled: false,
        children: [],
      },
      {
        key: 'manage',
        title: 'ANALYSTS',
        path: `/manage/cdfi/${cdfiConfig.cdfiId}/analysts`,
        icon: 'contacts',
        disabled: false,
        children: [],
      },
      {
        key: 'downloads',
        title: 'Downloads',
        path: '/',
        icon: 'downloadicon',
        disabled: false,
        children: [
          {
            key: 'factsheet',
            title: DownloadTitles.FACT_SHEET,
            path: '/',
            disabled: false,
            children: [],
          },
          {
            key: 'ratingcert',
            title: DownloadTitles.RATING_CERTIFICATE,
            path: '/',
            disabled: !isRated,
            children: [],
          },
          {
            key: 'aerislogos',
            title: 'Aeris-Rated Logos',
            path: `/manage/cdfi/${cdfiConfig.cdfiId}/ratings`,
            disabled: false,
            children: [],
          },
        ],
      },
      {
        key: 'aerisexplorer',
        title: 'CDFI EXPLORER',
        path: `/aerisexplorer/cdfi/${cdfiConfig.cdfiId}`,
        icon: 'auditicon',
        disabled: false,
        children: [],
      },
      {
        key: 'supporthistory',
        title: 'SUPPORT HISTORY',
        path: `/manage/cdfi/${cdfiConfig.cdfiId}/support-history`,
        icon: 'customerservice',
        disabled: false,
        children: [],
      },
    ],
    [UserRole.AERIS_ANALYST]: [
      {
        key: '',
        title: 'ACCESS CDFI',
        path: '/',
        divider: true,
      },
      {
        key: 'access',
        title: 'ORGANIZATION DETAILS',
        path: `/manage/cdfi/${cdfiConfig.cdfiId}/org-details`,
        icon: 'idcardicon',
        disabled: false,
        children: [],
      },
      {
        key: 'aerisexplorer',
        title: 'CDFI EXPLORER',
        path: `/aerisexplorer/cdfi/${cdfiConfig.cdfiId}`,
        icon: 'auditicon',
        disabled: false,
        children: [],
      },
      {
        key: 'access',
        title: 'RATINGS',
        path: `/manage/cdfi/${cdfiConfig.cdfiId}/ratings`,
        icon: 'staricon',
        disabled: false,
        children: [],
      },
      {
        key: 'access',
        title: 'SUBSCRIBERS',
        path: `/manage/cdfi/${cdfiConfig.cdfiId}/subscribers`,
        icon: 'filedoneicon',
        disabled: false,
        children: [],
      },
      {
        key: 'access',
        title: 'FINANCIALS',
        path: `/manage/cdfi/${cdfiConfig.cdfiId}/financials`,
        icon: 'dollaricon',
        disabled: false,
        children: [],
      },
      {
        key: 'access',
        title: 'LIBRARY',
        path: `/manage/cdfi/${cdfiConfig.cdfiId}/library`,
        icon: 'readicon',
        disabled: false,
        children: [],
      },
    ],
    [UserRole.CDFI]: [],
    [UserRole.SUBSCRIBER]: [],
    [UserRole.UNKNOWN]: [],
  };
};

export const adminSubscriberSelectedItems = (): Record<
  UserRole,
  ManagementMenuItem[]
> => {
  return {
    [UserRole.AERIS_ADMIN]: [
      {
        key: 'cdfiselector',
        title: 'CDFI SELECTOR',
        path: '/cdfiSelector',
        icon: 'filesearch',
      },
      {
        key: 'aerisexp',
        title: 'GLOBAL PEER GROUPS',
        path: '/aerisExplorer/global',
        icon: 'auditicon',
      },
      {
        key: '',
        title: 'ACCESS SUBSCRIBER',
        path: '/',
        divider: true,
      },
      {
        key: 'manage',
        title: 'DASHBOARD',
        path: `/manage/subscriber/${subscriberConfig.subscriberId}`,
        icon: 'dashboardicon',
        disabled: false,
        children: [],
      },
      {
        key: 'access',
        title: 'SUBSCRIPTIONS',
        path: `/manage/subscriber/${subscriberConfig.subscriberId}/subscriptions`,
        icon: 'staricon',
        disabled: false,
        children: [],
      },
      {
        key: 'access',
        title: 'ACCOUNT SUMMARY',
        path: `/manage/subscriber/${subscriberConfig.subscriberId}/account_summary`,
        icon: 'staricon',
        disabled: false,
        children: [],
      },
      {
        key: 'manage',
        title: 'CDFIs',
        path: `/manage/subscriber/${subscriberConfig.subscriberId}/cdfis`,
        icon: 'filedoneicon',
        disabled: false,
        children: [],
      },
      {
        key: 'access',
        title: 'CDFI EXPLORER',
        path: `/aerisexplorer/subscriber/${subscriberConfig.subscriberId}`,
        icon: 'auditicon',
        disabled: false,
        children: [],
      },
      {
        key: '',
        title: 'MANAGE SUBSCRIBER',
        path: '/',
        divider: true,
      },
      {
        key: 'manage',
        title: 'ORGANIZATION DETAILS',
        path: `/manage/subscriber/${subscriberConfig.subscriberId}/org-details`,
        icon: 'idcardicon',
        disabled: false,
        children: [],
      },
      {
        key: 'manage',
        title: 'CONTACTS',
        path: `/manage/subscriber/${subscriberConfig.subscriberId}/contacts`,
        icon: 'teamicon',
        disabled: false,
        children: [],
      },
      {
        key: 'manager',
        title: 'SUPPORT HISTORY',
        path: `/manage/subscriber/${subscriberConfig.subscriberId}/support-history`,
        icon: 'customerservice',
        disabled: false,
        children: [],
      },
    ],
    [UserRole.AERIS_STAFF]: [
      {
        key: 'cdfiselector',
        title: 'CDFI SELECTOR',
        path: '/cdfiSelector',
        icon: 'filesearch',
      },
      {
        key: 'aerisexp',
        title: 'GLOBAL PEER GROUPS',
        path: '/aerisExplorer/global',
        icon: 'auditicon',
      },
      {
        key: '',
        title: 'ACCESS SUBSCRIBER',
        path: '/',
        divider: true,
      },
      {
        key: 'manage',
        title: 'DASHBOARD',
        path: `/manage/subscriber/${subscriberConfig.subscriberId}`,
        icon: 'dashboardicon',
        disabled: false,
        children: [],
      },
      {
        key: 'access',
        title: 'SUBSCRIPTIONS',
        path: `/manage/subscriber/${subscriberConfig.subscriberId}/subscriptions`,
        icon: 'staricon',
        disabled: false,
        children: [],
      },
      {
        key: 'access',
        title: 'ACCOUNT SUMMARY',
        path: `/manage/subscriber/${subscriberConfig.subscriberId}/account_summary`,
        icon: 'staricon',
        disabled: false,
        children: [],
      },
      {
        key: 'manage',
        title: 'CDFIs',
        path: `/manage/subscriber/${subscriberConfig.subscriberId}/cdfis`,
        icon: 'filedoneicon',
        disabled: false,
        children: [],
      },
      {
        key: 'access',
        title: 'CDFI EXPLORER',
        path: `/aerisexplorer/subscriber/${subscriberConfig.subscriberId}`,
        icon: 'auditicon',
        disabled: false,
        children: [],
      },
      {
        key: '',
        title: 'MANAGE SUBSCRIBER',
        path: '/',
        divider: true,
      },
      {
        key: 'manage',
        title: 'ORGANIZATION DETAILS',
        path: `/manage/subscriber/${subscriberConfig.subscriberId}/org-details`,
        icon: 'idcardicon',
        disabled: false,
        children: [],
      },
      {
        key: 'manage',
        title: 'CONTACTS',
        path: `/manage/subscriber/${subscriberConfig.subscriberId}/contacts`,
        icon: 'teamicon',
        disabled: false,
        children: [],
      },
      {
        key: 'manager',
        title: 'SUPPORT HISTORY',
        path: `/manage/subscriber/${subscriberConfig.subscriberId}/support-history`,
        icon: 'customerservice',
        disabled: false,
        children: [],
      },
    ],
    [UserRole.CONTRACTOR]: [
      {
        key: 'cdfiselector',
        title: 'CDFI SELECTOR',
        path: '/cdfiSelector',
        icon: 'filesearch',
      },
      {
        key: '',
        title: 'ACCESS SUBSCRIBER',
        path: '/',
        divider: true,
      },
      {
        key: 'manage',
        title: 'DASHBOARD',
        path: `/manage/subscriber/${subscriberConfig.subscriberId}`,
        icon: 'dashboardicon',
        disabled: false,
        children: [],
      },
      {
        key: 'access',
        title: 'SUBSCRIPTIONS',
        path: `/manage/subscriber/${subscriberConfig.subscriberId}/subscriptions`,
        icon: 'staricon',
        disabled: false,
        children: [],
      },
      {
        key: 'access',
        title: 'ACCOUNT SUMMARY',
        path: `/manage/subscriber/${subscriberConfig.subscriberId}/account_summary`,
        icon: 'staricon',
        disabled: false,
        children: [],
      },
      {
        key: 'manage',
        title: 'CDFIs',
        path: `/manage/subscriber/${subscriberConfig.subscriberId}/cdfis`,
        icon: 'filedoneicon',
        disabled: false,
        children: [],
      },
      {
        key: 'access',
        title: 'CDFI EXPLORER',
        path: `/aerisexplorer/subscriber/${subscriberConfig.subscriberId}`,
        icon: 'auditicon',
        disabled: false,
        children: [],
      },
      {
        key: '',
        title: 'MANAGE SUBSCRIBER',
        path: '/',
        divider: true,
      },
      {
        key: 'manage',
        title: 'ORGANIZATION DETAILS',
        path: `/manage/subscriber/${subscriberConfig.subscriberId}/org-details`,
        icon: 'idcardicon',
        disabled: false,
        children: [],
      },
      {
        key: 'manage',
        title: 'CONTACTS',
        path: `/manage/subscriber/${subscriberConfig.subscriberId}/contacts`,
        icon: 'teamicon',
        disabled: false,
        children: [],
      },
      {
        key: 'manager',
        title: 'SUPPORT HISTORY',
        path: `/manage/subscriber/${subscriberConfig.subscriberId}/support-history`,
        icon: 'customerservice',
        disabled: false,
        children: [],
      },
    ],
    [UserRole.AERIS_ANALYST]: [],
    [UserRole.CDFI]: [],
    [UserRole.SUBSCRIBER]: [],
    [UserRole.UNKNOWN]: [],
  };
};
