import { UserRole } from 'types';
import { userStore } from '../../../../store';
import { ManagementMenuItem } from '../components/types';
import { DownloadTitles } from '../constants';

export const menuItemsByUser = (
  isRated?: boolean,
  isPublicNonSubscriberEnabled?: boolean,
): Record<UserRole, ManagementMenuItem[]> => {
  const aerisUsersTitle = isPublicNonSubscriberEnabled
    ? 'Aeris Users'
    : 'Aeris Admin/Analyst';
  const userItems = [
    {
      key: 'adminanalyst',
      title: aerisUsersTitle,
      path: '/manage/users',
      disabled: false,
    },
    {
      key: 'allUserslist',
      title: 'All Cloud Users',
      path: '/manage/all-users',
      disabled: false,
    },
  ];

  if (isPublicNonSubscriberEnabled)
    userItems.push({
      key: 'publicUserslist',
      title: 'Public Non-Subscribers',
      path: `/manage/public-users`,
      disabled: false,
    });
  return {
    [UserRole.AERIS_ADMIN]: [
      {
        key: 'cdfiselector',
        title: 'CDFI SELECTOR',
        path: '/cdfiSelector',
        icon: 'filesearch',
      },
      {
        key: 'aerisexp',
        title: 'GLOBAL PEER GROUPS',
        path: '/aerisExplorer/global',
        icon: 'auditicon',
      },
      {
        key: '',
        title: 'MANAGE',
        path: '/',
        divider: true,
      },
      {
        key: 'library',
        title: 'TOOLS AND RESOURCES',
        path: '/library',
        icon: 'bookicon',
        disabled: false,
        children: [],
      },
      {
        key: 'manageplatform',
        title: 'MANAGE PLATFORM',
        path: '/manage-platform',
        icon: 'barcharticon',
        disabled: false,
        children: [],
      },
      {
        key: 'reports',
        title: 'CUSTOM DATA REPORTS',
        path: '/custom-data-reports',
        icon: 'fileicon',
        disabled: false,
        children: [],
      },
      {
        key: 'organizations',
        title: 'ORGANIZATIONS',
        path: '/',
        icon: 'bookicon',
        children: [
          {
            key: 'createcdfi',
            title: 'Create CDFI',
            path: '/manage/organizations/create-cdfi',
            children: [],
            disabled: false,
          },
          {
            key: 'createsubscriber',
            title: 'Create Subscriber',
            path: '/manage/organizations/create-subscriber',
            disabled: false,
            children: [],
          },
          {
            key: 'allCloudOrganizations',
            title: 'All Cloud Organizations',
            path: '/manage/organizations/all-organizations',
            disabled: false,
          },
          {
            key: 'allCloudSubscribers',
            title: 'All Cloud Subscribers',
            path: '/manage/organizations/all-subscribers',
            disabled: false,
          },
        ],
      },
      {
        key: 'users',
        title: 'USERS',
        path: '/',
        icon: 'teamicon',
        children: userItems,
      },
      {
        key: 'ratingsdefinitions',
        title: 'RATINGS DEFINITIONS',
        path: '/ratings-definitions',
        icon: 'staricon',
        children: [],
      },
    ],
    [UserRole.SUBSCRIBER]: [
      {
        key: '',
        title: 'ACCESS',
        path: '/',
        divider: true,
      },
      {
        key: 'cdfiselector',
        title: 'CDFI SELECTOR',
        path: '/cdfiSelector',
        icon: 'filesearch',
        disabled: false,
      },
      {
        key: 'aerisexp',
        title: 'AERIS® EXPLORER',
        path: `/aerisExplorer/subscriber/${userStore.companyId}`,
        icon: 'auditicon',
        disabled: false,
      },
      {
        key: 'ratingsDistribution',
        title: 'AERIS® RATINGS DISTRIBUTION',
        path: '/ratings-distribution',
        icon: 'staricon',
        disabled: false,
      },
      {
        key: 'ratingsdefinitions',
        title: 'RATINGS DEFINITIONS',
        path: '/ratings-definitions',
        icon: 'staricon',
        children: [],
      },
      {
        key: 'myaccount',
        title: 'MY ACCOUNT',
        path: '/my-account',
        icon: 'teamicon',
        children: [],
      },
      {
        key: 'contacts',
        title: 'CONTACTS',
        path: `/contacts`,
        icon: 'teamicon',
        disabled: false,
        children: [],
      },
      {
        key: 'reports',
        title: 'CUSTOM DATA REPORTS',
        path: '/custom-data-reports',
        icon: 'reports',
        disabled: false,
        children: [],
      },
      {
        key: 'supportHistory',
        title: 'SUPPORT HISTORY',
        path: '/support-history',
        icon: 'customerservice',
        disabled: false,
        children: [],
      },
    ],
    [UserRole.AERIS_ANALYST]: [
      {
        key: 'cdfiselector',
        title: 'CDFI SELECTOR',
        path: '/cdfiSelector',
        icon: 'filesearch',
      },
      {
        key: 'library',
        title: 'TOOLS AND RESOURCES',
        path: '/library',
        icon: 'bookicon',
        disabled: false,
        children: [],
      },
    ],
    [UserRole.CDFI]: [
      {
        key: '',
        title: 'ACCESS',
        path: '/',
        divider: true,
      },
      {
        key: 'manage',
        title: 'LIBRARY',
        path: `/cdfi/${userStore.companyId}/library`,
        icon: 'readicon',
        disabled: false,
        children: [],
      },
      {
        key: 'manage',
        title: 'RATINGS',
        path: `/cdfi/${userStore.companyId}/ratings`,
        icon: 'staricon',
        disabled: false,
        children: [],
      },
      {
        key: 'manage',
        title: 'FINANCIALS',
        path: `/cdfi/${userStore.companyId}/financials`,
        icon: 'dollaricon',
        disabled: false,
        children: [],
      },
      {
        key: 'manage',
        title: 'SUBSCRIBERS',
        path: `/cdfi/${userStore.companyId}/subscribers`,
        icon: 'filedoneicon',
        disabled: false,
        children: [],
      },
      {
        key: 'manage',
        title: 'ORGANIZATION DETAILS',
        path: `/cdfi/${userStore.companyId}/org-details`,
        icon: 'idcardicon',
        disabled: false,
        children: [],
      },
      {
        key: 'contacts',
        title: 'CONTACTS',
        path: `/cdfi/${userStore.companyId}/contacts`,
        icon: 'teamicon',
        disabled: false,
        children: [],
      },
      {
        key: 'downloads',
        title: 'Downloads',
        path: '/',
        icon: 'downloadicon',
        disabled: false,
        children: [
          {
            key: 'factsheet',
            title: DownloadTitles.FACT_SHEET,
            path: '/',
            disabled: false,
            children: [],
          },
          {
            key: 'ratingcert',
            title: DownloadTitles.RATING_CERTIFICATE,
            path: '/',
            disabled: !isRated,
            children: [],
          },
          {
            key: 'aerislogos',
            title: 'Aeris-Rated Logos',
            path: `/cdfi/${userStore.companyId}/ratings`,
            disabled: false,
            children: [],
          },
        ],
      },
      {
        key: 'aerisexp',
        title: 'AERIS® EXPLORER',
        path: `/aerisExplorer/cdfi/${userStore.companyId}`,
        icon: 'auditicon',
      },
      {
        key: 'supporthistory',
        title: 'SUPPORT HISTORY',
        path: '/support-history',
        icon: 'customerservice',
        disabled: false,
        children: [],
      },
      {
        key: 'ratingsdefinitions',
        title: 'RATINGS DEFINITIONS',
        path: '/ratings-definitions',
        icon: 'staricon',
        children: [],
      },
      {
        key: 'reports',
        title: 'CUSTOM DATA REPORTS',
        path: '/custom-data-reports',
        icon: 'reports',
        disabled: false,
        children: [],
      },
    ],
    [UserRole.AERIS_STAFF]: [
      {
        key: 'cdfiselector',
        title: 'CDFI SELECTOR',
        path: '/cdfiSelector',
        icon: 'filesearch',
      },
      {
        key: 'aerisexp',
        title: 'GLOBAL PEER GROUPS',
        path: '/aerisExplorer/global',
        icon: 'auditicon',
      },
      {
        key: '',
        title: 'MANAGE',
        path: '/',
        divider: true,
      },
      {
        key: 'library',
        title: 'TOOLS AND RESOURCES',
        path: '/library',
        icon: 'bookicon',
        disabled: false,
        children: [],
      },
      {
        key: 'reports',
        title: 'CUSTOM DATA REPORTS',
        path: '/custom-data-reports',
        icon: 'fileicon',
        disabled: false,
        children: [],
      },
      {
        key: 'organizations',
        title: 'ORGANIZATIONS',
        path: '/',
        icon: 'bookicon',
        children: [
          {
            key: 'createcdfi',
            title: 'Create CDFI',
            path: '/manage/organizations/create-cdfi',
            children: [],
            disabled: false,
          },
          {
            key: 'createsubscriber',
            title: 'Create Subscriber',
            path: '/manage/organizations/create-subscriber',
            disabled: false,
            children: [],
          },
          {
            key: 'allCloudOrganizations',
            title: 'All Cloud Organizations',
            path: '/manage/organizations/all-organizations',
            disabled: false,
          },
          {
            key: 'allCloudSubscribers',
            title: 'All Cloud Subscribers',
            path: '/manage/organizations/all-subscribers',
            disabled: false,
          },
        ],
      },
      {
        key: 'users',
        title: 'USERS',
        path: '/',
        icon: 'teamicon',
        children: userItems,
      },
      {
        key: 'ratingsdefinitions',
        title: 'RATINGS DEFINITIONS',
        path: '/ratings-definitions',
        icon: 'staricon',
        children: [],
      },
    ],
    [UserRole.CONTRACTOR]: [
      {
        key: 'cdfiselector',
        title: 'CDFI SELECTOR',
        path: '/cdfiSelector',
        icon: 'filesearch',
      },
      {
        key: '',
        title: 'MANAGE',
        path: '/',
        divider: true,
      },
      {
        key: 'ratingsdefinitions',
        title: 'RATINGS DEFINITIONS',
        path: '/ratings-definitions',
        icon: 'staricon',
        children: [],
      },
    ],
    [UserRole.UNKNOWN]: [],
  };
};
